use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let generated = out_dir.join("target_paths.rs");

    let content = "// generated by build.rs\n";
    fs::write(&generated, content)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", generated.display()));

    println!("cargo:rerun-if-changed=build.rs");
}
